title: Talk like a Pirate
meta_title: Make your own webpage | Learn web development | Pirate Translator
meta_description: Make your own webpage and learn web development with the Raspberry Pi Foundation. Use HTML and JQuery to create a funny pirate translator.
hero_image: images/banner.png
description: Create a web page which can translate normal English text into pirate speak.
listed: false
copyedit: true
version: 4
last_tested: 2026-03-11
steps:
  - title: Introduction
  - title: Create the page layout
    completion:
      - engaged
  - title: Load jQuery when the page opens
  - title: Copy text as you type
  - title: Add pirate word replacements
    completion:
      - internal
  - title: Use regex for trickier pirate phrases
    completion:
      - external
